POST http://localhost:8080/auth/realms/fincycle/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=nest
&client_secret=250cfcc2-e274-49cc-a49b-695b335694b4
&grant_type=password
&username=user1@user.com
&password=123456